FROM openjdk:8
ARG projectName
ARG projectVersion

ADD build/distributions/${projectName}-${projectVersion}.tar /usr/

WORKDIR /usr/${projectName}-${projectVersion}
CMD ["bin/os-JavaMicroservice"] # script generated by gradle - TODO use ARG also

EXPOSE 8080
