FROM openjdk:8
ARG projectName

ADD build/distributions/${projectName}.tar /usr/

WORKDIR /usr/${projectName}
CMD ["bin/os-JavaMicroservice"] # script generated by gradle - TODO use ARG also

EXPOSE 8080
